[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
debug = false
strip = true
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false

[dependencies]
regex = "*"
counter = "*"
rustc-hash = "*"
criterion = "0.4.0"

[lib]
name = "aoc"
path = "lib.rs"

[[bin]]
name = "2022_01"
path = "2022/01.rs"

[[bench]]
name = "2022"
path = "2022/01.rs"
harness = false
